@echo off
TITLE Calgary Grocery Hub - Claude Edition
echo [1/3] Processing Flyer Extraction and AI Analysis...
python get_deals.py
echo [2/4] Generating Weekly Reports...
set PYTHONIOENCODING=utf-8
python weekly_report_generator.py
echo [3/4] Pushing to GitHub...
call push_to_github.bat
echo [4/4] Complete! Opening Current Flyer Report...
start current_flyers.csv
pause
